import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Head from "next/head";

function AboutUS() {
    return (
        <section>
            {/* call function NavigationBar */}
            <Head>
                <title>Find University</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <Navbar />

            <section className="container">
                <div className="desc-object">
                    <h1>គោលបំណង</h1>
                    <p>
                        FUND UNIVERSITY គឺជា
                        វេបសាយបង្កើតឡើងតម្រូវទៅលើសិស្សដែរទើបនឹងបញ្ចប់ថ្នាក់ទី១២ក៏ដូចជាទៅកាន់អ្នកដែលចង់ដឹងនៅព័ត៏មានសាលាសកលដែលមានក្នុងប្រទេសកម្ពុជាផងដែរ។
                    </p>
                    <div className="row-container">
                        <h1>ព័ត៍មានដែរមាន</h1>
                        <div className="row">
                            <div className="box">ថ្នាក់បរិញ្ញាបត្រ</div>
                            <div className="box">កម្មវិធីសិក្សា</div>
                            <div className="box">ទំនាក់ទំនង</div>
                        </div>
                    </div>
                </div>
                <div className="ourteam">
                    <h1>បង្កើតដោយក្រុមនិស្សិត</h1>
                    <div className="member">
                        <div className="name">សមាជិកក្រុម</div>
                        <div className="member-name">
                            <p>CHHOUN SEANGLY</p>
                            <p>MUNY ROTH</p>
                            <p>REN CHEARIKA</p>
                            <p>SENG VUTTHEA</p>
                        </div>
                    </div>
                </div>
            </section>
            {/* call function footer */}
            <Footer />
        </section>
    );
}

export default AboutUS;
